theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'

  menu:
    primary:
      level_2:
        title:
          active: true

  components:
    lightbox:
      disabled: false
      in_hero:
        disabled: true

  image_sizes:
    sections:
      home:
        hero:
          desktop: 1560
          additionnal:
            - rule: "min-width: 1560px"
              size: 2096